# Theme
include                    ./theme.conf

# Font
font_family                Google Sans Mono
bold_font                  auto
italic_font                auto
bold_italic_font           auto
font_size                  10.0

# Background
background_opacity         0.85
dynamic_background_opacity yes

# Cursor
shell_integration          no-cursor
