-- require('fowmind.plugins.nvim-treesitter')
require('fowmind.plugins.neo-tree')
require('fowmind.plugins.lualine')
require('fowmind.plugins.bufferline')
require('fowmind.plugins.comment')
require('fowmind.plugins.colorizer')
-- require('fowmind.plugins.transparent')
require('fowmind.plugins.luasnip')
require('fowmind.plugins.nvim-lspconfig')
require('fowmind.plugins.nvim-cmp')
require('fowmind.plugins.telescope')
require('fowmind.plugins.toggleterm')
-- require('fowmind.plugins.conform')
require('fowmind.plugins.nvim-autopairs')
require('fowmind.plugins.tailwind-tools')
